// Catálogo de Bichinhos Mascotes que ensinam o Alfabeto em LIBRAS
import mascotA from "@/assets/bichinhos/mascot_a.jpg";
import mascotB from "@/assets/bichinhos/mascot_b.jpg";
import mascotC from "@/assets/bichinhos/mascot_c.jpg";
import mascotD from "@/assets/bichinhos/mascot_d.jpg";
import mascotE from "@/assets/bichinhos/mascot_e.jpg";

export type AnimalMascot = {
  letter: string;
  animalName: string;
  species: string;
  emoji: string;
  image?: string;
  tone: string;
  pawDescription: string;
  librasExplanation: string;
  cheerMessage: string;
  badgeBg: string;
};

export const ANIMAL_MASCOTS: Record<string, AnimalMascot> = {
  A: {
    letter: "A",
    animalName: "Capivarinha Luvi",
    species: "Capivara",
    emoji: "🦫",
    image: mascotA,
    tone: "bg-sunshine",
    badgeBg: "from-amber-400 to-orange-500",
    pawDescription: "Punho fechado com o polegar reto encostado na lateral do indicador.",
    librasExplanation: "A Capivarinha Luvi fecha a patinha com o polegar ao lado para fazer a Letra A em LIBRAS!",
    cheerMessage: "Incrível! A Capivarinha Luvi adorou ver você fazer a Letra A!",
  },
  B: {
    letter: "B",
    animalName: "Coelhinho Theo",
    species: "Coelho",
    emoji: "🐰",
    image: mascotB,
    tone: "bg-sky",
    badgeBg: "from-sky-400 to-blue-600",
    pawDescription: "Quatro dedos estendidos para cima e polegar dobrado na palma.",
    librasExplanation: "O Coelhinho Theo ergue os 4 dedinhos juntos e dobra o polegar na frente da palma para a Letra B!",
    cheerMessage: "Saltando de alegria! O Coelhinho Theo manda os parabéns pela Letra B!",
  },
  C: {
    letter: "C",
    animalName: "Gatinha Mel",
    species: "Gatinha",
    emoji: "🐱",
    image: mascotC,
    tone: "bg-coral",
    badgeBg: "from-rose-400 to-pink-600",
    pawDescription: "Dedos curvados formando um semicírculo aberto como a letra C.",
    librasExplanation: "A Gatinha Mel curva a patinha formando um arco suave como a Letra C!",
    cheerMessage: "Miau-ravilhoso! A Gatinha Mel comemora seu acerto da Letra C!",
  },
  D: {
    letter: "D",
    animalName: "Dinossauro Dino",
    species: "Dino",
    emoji: "🦖",
    image: mascotD,
    tone: "bg-mint",
    badgeBg: "from-emerald-400 to-teal-600",
    pawDescription: "Apenas o dedo indicador apontando para cima e demais dedos tocando o polegar.",
    librasExplanation: "O Dino aponta o indicador para o alto e fecha os outros dedinhos no polegar para a Letra D!",
    cheerMessage: "Rugido de campeão! O Dino adorou sua Letra D em LIBRAS!",
  },
  E: {
    letter: "E",
    animalName: "Elefantinho Nino",
    species: "Elefante",
    emoji: "🐘",
    image: mascotE,
    tone: "bg-grape",
    badgeBg: "from-purple-400 to-indigo-600",
    pawDescription: "Todos os 4 dedos dobrados para baixo com as pontas repousando no polegar dobrado.",
    librasExplanation: "O Elefantinho Nino dobra as pontinhas dos dedos apoiadas no polegar para a Letra E!",
    cheerMessage: "Tromba de alegria! O Elefantinho Nino celebra sua Letra E perfeita!",
  },
  F: {
    letter: "F",
    animalName: "Foquinha Pipoca",
    species: "Foca",
    emoji: "🦭",
    image: mascotA, // fallback
    tone: "bg-sky",
    badgeBg: "from-cyan-400 to-blue-500",
    pawDescription: "Indicador dobrado para baixo com o polegar por FORA dele e outros 3 dedos eretos.",
    librasExplanation: "A Foquinha Pipoca coloca o polegar por FORA do indicador para fazer a Letra F em LIBRAS!",
    cheerMessage: "Palminhas da Foquinha Pipoca! Você acertou a Letra F com maestria!",
  },
  G: {
    letter: "G",
    animalName: "Girafinha Gigi",
    species: "Girafa",
    emoji: "🦒",
    image: mascotD,
    tone: "bg-sunshine",
    badgeBg: "from-yellow-400 to-amber-600",
    pawDescription: "Indicador apontando para cima e polegar estendido ao lado formando uma haste.",
    librasExplanation: "A Girafinha Gigi estica o dedinho para cima como seu pescoço alto para a Letra G!",
    cheerMessage: "Lá do alto a Girafinha Gigi comemora sua Letra G!",
  },
  H: {
    letter: "H",
    animalName: "Hipopótamo Pipo",
    species: "Hipopótamo",
    emoji: "🦛",
    image: mascotB,
    tone: "bg-mint",
    badgeBg: "from-teal-400 to-cyan-600",
    pawDescription: "Indicador e médio estendidos com polegar no meio, girando suavemente o pulso.",
    librasExplanation: "O Hippo Pipo faz o sinal em 'V' com o polegar no meio e dá um giro alegre para a Letra H!",
    cheerMessage: "Splash de festa! O Hippo Pipo adorou seu movimento da Letra H!",
  },
  I: {
    letter: "I",
    animalName: "Iguana Izi",
    species: "Iguana",
    emoji: "🦎",
    image: mascotC,
    tone: "bg-neon",
    badgeBg: "from-lime-400 to-green-600",
    pawDescription: "Mão fechada com apenas o dedo mínimo (mindinho) estendido para cima.",
    librasExplanation: "A Iguana Izi levanta só o dedinho mindinho bem firme para a Letra I!",
    cheerMessage: "Super esperta! A Iguana Izi aprovou sua Letra I de primeira!",
  },
  J: {
    letter: "J",
    animalName: "Jacarezinho Joca",
    species: "Jacaré",
    emoji: "🐊",
    image: mascotD,
    tone: "bg-mint",
    badgeBg: "from-green-500 to-emerald-700",
    pawDescription: "Mão em 'I' (mindinho ereto) desenhando a curva da letra J no ar.",
    librasExplanation: "O Jacarezinho Joca usa o mindinho para desenhar um anzol no ar para a Letra J!",
    cheerMessage: "Croc croc de vitória! O Jacarezinho Joca celebra seu traçado da Letra J!",
  },
  K: {
    letter: "K",
    animalName: "Coala Kiki",
    species: "Coala",
    emoji: "🐨",
    image: mascotE,
    tone: "bg-grape",
    badgeBg: "from-fuchsia-500 to-purple-700",
    pawDescription: "Indicador e médio em 'V' com o polegar entre eles, subindo levemente num impulso.",
    librasExplanation: "O Coala Kiki faz o formato com o dedão no meio e dá um saltinho para cima para a Letra K!",
    cheerMessage: "Abraço de Coala! O Coala Kiki ficou radiante com sua Letra K!",
  },
  L: {
    letter: "L",
    animalName: "Leãozinho Léo",
    species: "Leão",
    emoji: "🦁",
    image: mascotA,
    tone: "bg-coral",
    badgeBg: "from-orange-500 to-amber-600",
    pawDescription: "Indicador para cima e polegar aberto a 90 graus formando um 'L' perfeito.",
    librasExplanation: "O Leãozinho Léo abre o indicador e o polegar formando a Letra L como sua juba!",
    cheerMessage: "Rugido de ouro! O Leãozinho Léo declara que sua Letra L ficou impecável!",
  },
  M: {
    letter: "M",
    animalName: "Macaquinho Mico",
    species: "Macaco",
    emoji: "🐵",
    image: mascotB,
    tone: "bg-sunshine",
    badgeBg: "from-amber-500 to-yellow-600",
    pawDescription: "Três dedos (indicador, médio e anelar) estendidos para BAIXO apoiados no polegar.",
    librasExplanation: "O Macaquinho Mico aponta 3 dedinhos para baixo como galhos da árvore para a Letra M!",
    cheerMessage: "Pulos de alegria! O Macaquinho Mico adora ver sua Letra M!",
  },
  N: {
    letter: "N",
    animalName: "Narval Nino",
    species: "Narval",
    emoji: "🐋",
    image: mascotC,
    tone: "bg-sky",
    badgeBg: "from-sky-500 to-blue-700",
    pawDescription: "Dois dedos (indicador e médio) estendidos para BAIXO sobre o polegar.",
    librasExplanation: "O Narval Nino aponta 2 dedinhos para baixo para a Letra N!",
    cheerMessage: "Mergulho de campeão! O Narval Nino manda saudações pela Letra N!",
  },
  O: {
    letter: "O",
    animalName: "Ovelhinha Olívia",
    species: "Ovelha",
    emoji: "🐑",
    image: mascotE,
    tone: "bg-coral",
    badgeBg: "from-pink-400 to-rose-600",
    pawDescription: "Todos os 4 dedos e o polegar unidos pelas pontas formando um círculo 'O' fechado.",
    librasExplanation: "A Ovelhinha Olívia junta todas as pontinhas dos dedos formando uma bolinha 'O'!",
    cheerMessage: "Mééé de parabéns! A Ovelhinha Olívia aplaude sua Letra O!",
  },
  P: {
    letter: "P",
    animalName: "Pandinha Pan",
    species: "Panda",
    emoji: "🐼",
    image: mascotA,
    tone: "bg-grape",
    badgeBg: "from-indigo-400 to-purple-600",
    pawDescription: "Configuração do 'K' (indicador e médio com polegar no meio) com a mão apontada na horizontal.",
    librasExplanation: "O Pandinha Pan posiciona os dedos na horizontal para a Letra P!",
    cheerMessage: "Fofura total! O Pandinha Pan comemora sua Letra P certinha!",
  },
  Q: {
    letter: "Q",
    animalName: "Quokka Quico",
    species: "Quokka",
    emoji: "🦘",
    image: mascotD,
    tone: "bg-mint",
    badgeBg: "from-emerald-500 to-teal-700",
    pawDescription: "Indicador e polegar estendidos e apontados para BAIXO em formato de pinça.",
    librasExplanation: "O Quokka Quico aponta o indicador e polegar para baixo para a Letra Q!",
    cheerMessage: "O sorriso mais feliz do mundo! O Quokka Quico aplaudiu sua Letra Q!",
  },
  R: {
    letter: "R",
    animalName: "Raposinha Rubi",
    species: "Raposa",
    emoji: "🦊",
    image: mascotB,
    tone: "bg-coral",
    badgeBg: "from-orange-500 to-rose-600",
    pawDescription: "Dedo médio cruzado sobre o indicador estendido (dedos cruzados da sorte).",
    librasExplanation: "A Raposinha Rubi cruza o dedinho médio no indicador como sinal de sorte para a Letra R!",
    cheerMessage: "Astuta e brilhante! A Raposinha Rubi celebra sua Letra R!",
  },
  S: {
    letter: "S",
    animalName: "Sapinho Sapeca",
    species: "Sapo",
    emoji: "🐸",
    image: mascotC,
    tone: "bg-neon",
    badgeBg: "from-lime-500 to-green-700",
    pawDescription: "Punho fechado com o polegar cruzado sobre a FRENTE dos dedos indicador e médio.",
    librasExplanation: "O Sapinho Sapeca fecha o punho e cruza o polegar na frente para a Letra S!",
    cheerMessage: "Pulo alto de comemoração! O Sapinho Sapeca aprovou sua Letra S!",
  },
  T: {
    letter: "T",
    animalName: "Tartaruga Tatá",
    species: "Tartaruga",
    emoji: "🐢",
    image: mascotD,
    tone: "bg-mint",
    badgeBg: "from-teal-500 to-emerald-700",
    pawDescription: "Indicador dobrado com o polegar por DENTRO dele (polegar escondido) e 3 dedos eretos.",
    librasExplanation: "A Tartaruga Tatá esconde o polegar por DENTRO do indicador como em seu casco para a Letra T!",
    cheerMessage: "Passo firme e campeão! A Tartaruga Tatá comemora sua Letra T!",
  },
  U: {
    letter: "U",
    animalName: "Ursinho Uli",
    species: "Urso",
    emoji: "🐻",
    image: mascotA,
    tone: "bg-sunshine",
    badgeBg: "from-amber-600 to-yellow-700",
    pawDescription: "Indicador e médio estendidos e bem UNIDOS para cima.",
    librasExplanation: "O Ursinho Uli estica 2 dedinhos bem coladinhos para cima para a Letra U!",
    cheerMessage: "Abraço de urso carinhoso! O Ursinho Uli adorou sua Letra U!",
  },
  V: {
    letter: "V",
    animalName: "Vaquinha Vivi",
    species: "Vaca",
    emoji: "🐮",
    image: mascotB,
    tone: "bg-coral",
    badgeBg: "from-rose-500 to-pink-700",
    pawDescription: "Indicador e médio estendidos e AFASTADOS formando a letra 'V' da paz.",
    librasExplanation: "A Vaquinha Vivi afasta os dois dedinhos em 'V' como seus chifrinhos para a Letra V!",
    cheerMessage: "Mu-muito bem! A Vaquinha Vivi festeja sua Letra V!",
  },
  W: {
    letter: "W",
    animalName: "Wombat Wally",
    species: "Wombat",
    emoji: "🦡",
    image: mascotE,
    tone: "bg-grape",
    badgeBg: "from-purple-500 to-indigo-700",
    pawDescription: "Três dedos (indicador, médio e anelar) estendidos para CIMA e afastados.",
    librasExplanation: "O Wombat Wally levanta 3 dedinhos abertos para o alto para a Letra W!",
    cheerMessage: "Super divertido! O Wombat Wally manda parabéns pela Letra W!",
  },
  X: {
    letter: "X",
    animalName: "Pássaro Xexéu",
    species: "Pássaro",
    emoji: "🦜",
    image: mascotC,
    tone: "bg-sky",
    badgeBg: "from-cyan-500 to-blue-600",
    pawDescription: "Indicador em gancho puxando suavemente para trás em direção ao corpo.",
    librasExplanation: "O Pássaro Xexéu curva o dedinho como bico e puxa para trás para a Letra X!",
    cheerMessage: "Canto de festa! O Pássaro Xexéu comemora sua Letra X em LIBRAS!",
  },
  Y: {
    letter: "Y",
    animalName: "Yak Yoyo",
    species: "Yak",
    emoji: "🦬",
    image: mascotA,
    tone: "bg-sunshine",
    badgeBg: "from-yellow-500 to-orange-600",
    pawDescription: "Polegar e mínimo estendidos para os lados (Hang Loose) balançando suavemente.",
    librasExplanation: "O Yak Yoyo abre o dedão e o mindinho para os lados para a Letra Y!",
    cheerMessage: "Hang loose campeão! O Yak Yoyo amou sua Letra Y!",
  },
  Z: {
    letter: "Z",
    animalName: "Zebrinha Zazá",
    species: "Zebra",
    emoji: "🦓",
    image: mascotD,
    tone: "bg-grape",
    badgeBg: "from-slate-700 to-slate-900",
    pawDescription: "Indicador estendido desenhando um 'Z' em zigue-zague no ar.",
    librasExplanation: "A Zebrinha Zazá usa o dedinho indicador para desenhar as listras do 'Z' no ar!",
    cheerMessage: "Listras douradas de ouro! A Zebrinha Zazá fecha com chave de ouro sua Letra Z!",
  },
};

export function getAnimalMascot(letter: string): AnimalMascot {
  const normalized = (letter || "A").toUpperCase().trim().charAt(0);
  return ANIMAL_MASCOTS[normalized] || ANIMAL_MASCOTS["A"];
}
