/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LicaoRouteImport } from './routes/licao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TrilhaRouteImport } from './routes/trilha'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as OnboardingCoresAmareloRouteImport } from './routes/onboarding/cores/amarelo'
import { Route as OnboardingCoresAzulRouteImport } from './routes/onboarding/cores/azul'
import { Route as OnboardingCoresRoxoRouteImport } from './routes/onboarding/cores/roxo'
import { Route as OnboardingCoresVerdeRouteImport } from './routes/onboarding/cores/verde'
import { Route as OnboardingCoresVermelhoRouteImport } from './routes/onboarding/cores/vermelho'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicaoRoute = LicaoRouteImport.update({
  id: '/licao',
  path: '/licao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaRoute = TrilhaRouteImport.update({
  id: '/trilha',
  path: '/trilha',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCoresAmareloRoute = OnboardingCoresAmareloRouteImport.update({
  id: '/cores/amarelo',
  path: '/cores/amarelo',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCoresAzulRoute = OnboardingCoresAzulRouteImport.update({
  id: '/cores/azul',
  path: '/cores/azul',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCoresRoxoRoute = OnboardingCoresRoxoRouteImport.update({
  id: '/cores/roxo',
  path: '/cores/roxo',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCoresVerdeRoute = OnboardingCoresVerdeRouteImport.update({
  id: '/cores/verde',
  path: '/cores/verde',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCoresVermelhoRoute = OnboardingCoresVermelhoRouteImport.update({
  id: '/cores/vermelho',
  path: '/cores/vermelho',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/licao': typeof LicaoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/trilha': typeof TrilhaRoute
  '/student/profile': typeof StudentProfileRoute
  '/onboarding/cores/amarelo': typeof OnboardingCoresAmareloRoute
  '/onboarding/cores/azul': typeof OnboardingCoresAzulRoute
  '/onboarding/cores/roxo': typeof OnboardingCoresRoxoRoute
  '/onboarding/cores/verde': typeof OnboardingCoresVerdeRoute
  '/onboarding/cores/vermelho': typeof OnboardingCoresVermelhoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/licao': typeof LicaoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/trilha': typeof TrilhaRoute
  '/student/profile': typeof StudentProfileRoute
  '/onboarding/cores/amarelo': typeof OnboardingCoresAmareloRoute
  '/onboarding/cores/azul': typeof OnboardingCoresAzulRoute
  '/onboarding/cores/roxo': typeof OnboardingCoresRoxoRoute
  '/onboarding/cores/verde': typeof OnboardingCoresVerdeRoute
  '/onboarding/cores/vermelho': typeof OnboardingCoresVermelhoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/licao': typeof LicaoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/trilha': typeof TrilhaRoute
  '/student/profile': typeof StudentProfileRoute
  '/onboarding/cores/amarelo': typeof OnboardingCoresAmareloRoute
  '/onboarding/cores/azul': typeof OnboardingCoresAzulRoute
  '/onboarding/cores/roxo': typeof OnboardingCoresRoxoRoute
  '/onboarding/cores/verde': typeof OnboardingCoresVerdeRoute
  '/onboarding/cores/vermelho': typeof OnboardingCoresVermelhoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/licao'
    | '/login'
    | '/onboarding'
    | '/trilha'
    | '/student/profile'
    | '/onboarding/cores/amarelo'
    | '/onboarding/cores/azul'
    | '/onboarding/cores/roxo'
    | '/onboarding/cores/verde'
    | '/onboarding/cores/vermelho'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/licao'
    | '/login'
    | '/onboarding'
    | '/trilha'
    | '/student/profile'
    | '/onboarding/cores/amarelo'
    | '/onboarding/cores/azul'
    | '/onboarding/cores/roxo'
    | '/onboarding/cores/verde'
    | '/onboarding/cores/vermelho'
  id:
    | '__root__'
    | '/'
    | '/licao'
    | '/login'
    | '/onboarding'
    | '/trilha'
    | '/student/profile'
    | '/onboarding/cores/amarelo'
    | '/onboarding/cores/azul'
    | '/onboarding/cores/roxo'
    | '/onboarding/cores/verde'
    | '/onboarding/cores/vermelho'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LicaoRoute: typeof LicaoRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  TrilhaRoute: typeof TrilhaRoute
  StudentProfileRoute: typeof StudentProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licao': {
      id: '/licao'
      path: '/licao'
      fullPath: '/licao'
      preLoaderRoute: typeof LicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha': {
      id: '/trilha'
      path: '/trilha'
      fullPath: '/trilha'
      preLoaderRoute: typeof TrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/cores/amarelo': {
      id: '/onboarding/cores/amarelo'
      path: '/cores/amarelo'
      fullPath: '/onboarding/cores/amarelo'
      preLoaderRoute: typeof OnboardingCoresAmareloRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/cores/azul': {
      id: '/onboarding/cores/azul'
      path: '/cores/azul'
      fullPath: '/onboarding/cores/azul'
      preLoaderRoute: typeof OnboardingCoresAzulRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/cores/roxo': {
      id: '/onboarding/cores/roxo'
      path: '/cores/roxo'
      fullPath: '/onboarding/cores/roxo'
      preLoaderRoute: typeof OnboardingCoresRoxoRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/cores/verde': {
      id: '/onboarding/cores/verde'
      path: '/cores/verde'
      fullPath: '/onboarding/cores/verde'
      preLoaderRoute: typeof OnboardingCoresVerdeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/cores/vermelho': {
      id: '/onboarding/cores/vermelho'
      path: '/cores/vermelho'
      fullPath: '/onboarding/cores/vermelho'
      preLoaderRoute: typeof OnboardingCoresVermelhoRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingCoresAmareloRoute: typeof OnboardingCoresAmareloRoute
  OnboardingCoresAzulRoute: typeof OnboardingCoresAzulRoute
  OnboardingCoresRoxoRoute: typeof OnboardingCoresRoxoRoute
  OnboardingCoresVerdeRoute: typeof OnboardingCoresVerdeRoute
  OnboardingCoresVermelhoRoute: typeof OnboardingCoresVermelhoRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCoresAmareloRoute: OnboardingCoresAmareloRoute,
  OnboardingCoresAzulRoute: OnboardingCoresAzulRoute,
  OnboardingCoresRoxoRoute: OnboardingCoresRoxoRoute,
  OnboardingCoresVerdeRoute: OnboardingCoresVerdeRoute,
  OnboardingCoresVermelhoRoute: OnboardingCoresVermelhoRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LicaoRoute: LicaoRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  TrilhaRoute: TrilhaRoute,
  StudentProfileRoute: StudentProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
