/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LicaoRouteImport } from './routes/licao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TrilhaRouteImport } from './routes/trilha'
import { Route as StudentProfileRouteImport } from './routes/student/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicaoRoute = LicaoRouteImport.update({
  id: '/licao',
  path: '/licao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaRoute = TrilhaRouteImport.update({
  id: '/trilha',
  path: '/trilha',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/licao': typeof LicaoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/trilha': typeof TrilhaRoute
  '/student/profile': typeof StudentProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/licao': typeof LicaoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/trilha': typeof TrilhaRoute
  '/student/profile': typeof StudentProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/licao': typeof LicaoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/trilha': typeof TrilhaRoute
  '/student/profile': typeof StudentProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/licao' | '/login' | '/onboarding' | '/trilha' | '/student/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/licao' | '/login' | '/onboarding' | '/trilha' | '/student/profile'
  id:
    | '__root__'
    | '/'
    | '/licao'
    | '/login'
    | '/onboarding'
    | '/trilha'
    | '/student/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LicaoRoute: typeof LicaoRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  TrilhaRoute: typeof TrilhaRoute
  StudentProfileRoute: typeof StudentProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licao': {
      id: '/licao'
      path: '/licao'
      fullPath: '/licao'
      preLoaderRoute: typeof LicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha': {
      id: '/trilha'
      path: '/trilha'
      fullPath: '/trilha'
      preLoaderRoute: typeof TrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LicaoRoute: LicaoRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  TrilhaRoute: TrilhaRoute,
  StudentProfileRoute: StudentProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
