// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enoftahwcfttmefmavji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVub2Z0YWh3Y2Z0dG1lZm1hdmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk1MTM1MDgsImV4cCI6MjEwNTA4OTUwOH0.kAc6VsVEd6rqWc6oeLgWxxm1u_2weLn1Alw5M2P-kmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});